Repository 9weeks-app-web/Team-7, pull requests merged in 2024-01, with the labels that each got.

#31 Feat: 회원가입 메인페이지 구현
  public/bgThumbnail.svg
  public/checkedThumbnail.svg
  src/components/join/EmailCheckbox.tsx
  src/components/join/EmailForm.tsx
  src/components/join/EmailFormItems.tsx
  src/components/join/OnboardingForm.tsx
  src/components/onboarding/ListItem.tsx
  src/pages/JoinComplete.tsx
  src/pages/JoinEmail.tsx
  src/pages/Onboarding.tsx
  src/types/joinFormTypes.ts
  tailwind.config.ts
Labels: Feat

#34 [Style] 중복된 title 로고 제거
  public/logoSfackTitle.svg
  public/titleLogoSfac.svg
  src/components/join/SnsJoinForm.tsx
  src/pages/Auth.tsx
  src/pages/Onboarding.tsx
Labels: Rename, Remove

#35 Feat: 비밀번호 변경 페이지 구현
  .husky/commit-msg
  src/pages/ChangePassword.tsx
  src/types/changePasswordFormTypes.ts
Labels: Feat

#36 Feat: 페이지별 라우터 연결 및 회원 가입 로직 결합
  src/App.tsx
  src/components/common/PhoneCertification.tsx
  src/components/join/SnsJoinForm.tsx
  src/components/login/AuthForm.tsx
  src/components/nickname/NicknameCheckbox.tsx
  src/pages/Auth.tsx
  src/pages/ChangePassword.tsx
  src/pages/Home.tsx
  src/pages/Join.tsx
  src/pages/JoinEmail.tsx
  src/pages/Nickname.tsx
  src/pages/Onboarding.tsx
  src/pages/ProtectedRouter.tsx
  src/pages/RedirectSignup.tsx
  src/pages/Signup.tsx
  src/store/counterSlice.ts
  src/store/index.ts
  src/store/joinSlice.ts
  src/types/formInputTypes.ts
Labels: Feat

#39 Style: 일부 페이지 아이콘 변경 및 색상 변경
  public/appleIcon.svg
  public/facebookIcon.svg
  public/googleIcon.svg
  public/kakaoIcon.svg
  public/naverIcon.svg
  src/components/join/SnsJoinForm.tsx
  src/pages/Onboarding.tsx
Labels: Style

#41 [Feature] 비밀번호 찾기 페이지 구현
  .husky/commit-msg.js
  src/App.tsx
  src/components/common/ErrorText.tsx
  src/components/common/FormInput.tsx
  src/components/login/AuthForm.tsx
  src/components/password/FindPasswordForm.tsx
  src/constants/errorMessages.ts
  src/hooks/useModal.tsx
  src/mocks/mockUser.ts
  src/pages/ChangePassword.tsx
  src/pages/FindPassword.tsx
  src/pages/Home.tsx
  src/store/authSlice.ts
  src/types/loginTypes.ts
  src/types/passwordTypes.ts
Labels: Feat

#45 Feat/portfolio 구현
  public/heart.svg
  public/portfolio/badge_pick.svg
  public/portfolio/badge_premium.svg
  public/portfolio/badge_type.svg
  public/portfolio/portfolioThumbnail_1.png
  public/portfolio/portfolioThumbnail_10.png
  public/portfolio/portfolioThumbnail_11.png
  public/portfolio/portfolioThumbnail_12.png
  public/portfolio/portfolioThumbnail_13.png
  public/portfolio/portfolioThumbnail_14.png
  public/portfolio/portfolioThumbnail_15.png
  public/portfolio/portfolioThumbnail_16.png
  public/portfolio/portfolioThumbnail_2.png
  public/portfolio/portfolioThumbnail_3.png
  public/portfolio/portfolioThumbnail_4.png
  public/portfolio/portfolioThumbnail_5.png
  public/portfolio/portfolioThumbnail_6.png
  public/portfolio/portfolioThumbnail_7.png
  public/portfolio/portfolioThumbnail_8.png
  public/portfolio/portfolioThumbnail_9.png
  public/portfolio/profile_1.png
  public/portfolio/profile_10.png
  public/portfolio/profile_11.png
  public/portfolio/profile_12.png
  public/portfolio/profile_13.png
  public/portfolio/profile_14.png
  public/portfolio/profile_2.png
  public/portfolio/profile_3.png
  public/portfolio/profile_4.png
  public/portfolio/profile_5.png
  public/portfolio/profile_6.png
  public/portfolio/profile_7.png
  public/portfolio/profile_8.png
  public/portfolio/profile_9.png
  public/view.svg
  src/components/portfolio/PortfolioBox.tsx
  src/components/portfolio/PortfolioList.tsx
  src/index.css
  src/mocks/mockPortfolio.ts
  src/types/portfolioBoxTypes.ts
Labels: Feat

#43 Feat: 배너 슬라이드 구현
  package.json
  public/BannerSlideLeft.svg
  public/BannerSlideRight.svg
  public/pcEventBanner1.png
  public/pcEventBanner2.png
  public/pcEventBanner3.png
  public/pcEventBanner4.png
  public/pcEventBanner5.png
  src/components/banner/Banner.styles.ts
  src/components/banner/Banner.tsx
  src/components/banner/nextArrow.tsx
  src/components/banner/prevArrow.tsx
  src/components/carousel/Banner.tsx
  src/constants/banner.ts
Labels: Feat

#50 Update: 회원가입 완료 이미지 추가
  public/joinComplete.png
  src/pages/JoinComplete.tsx
Labels: Style

#46 Feat: FilterPopupMenu 제작
  public/downArrowNeutral.svg
  public/leftArrowPrimary.svg
  public/rightArrowNeutral.svg
  public/rightArrowPrimary.svg
  public/upArrowPrimary.svg
  src/components/filterPopup/FilterPopup.tsx
  src/components/filterPopup/PopupCategory.tsx
  src/components/filterPopup/PopupMainCategoryItem.tsx
  src/components/filterPopup/PopupMenus.tsx
  src/components/filterPopup/PopupSubCategoryItem.tsx
  src/constants/categoryList.ts
  src/types/filterMenuTypes.ts
  tailwind.config.ts
Labels: Feat

#48 Feat: 합격자들의 포트폴리오 슬라이드
  package.json
  public/arrowLeft.svg
  public/arrowRight.svg
  public/corporateGoogle.png
  public/corporateKakao.png
  public/corporateNaver.png
  public/corporateSamsung.png
  public/lockCircle.svg
  src/components/successfulPortfolio/LeftContainer.tsx
  src/components/successfulPortfolio/RightContainer.tsx
  src/components/successfulPortfolio/SuccessfulPortfolio.styles.ts
  src/components/successfulPortfolio/SuccessfulPortfolio.tsx
  src/constants/SuccessfulPortfolio.ts
Labels: Chore, Feat

#51 [Feature] 아이디 찾기 페이지 구현
  src/App.tsx
  src/components/find/password/FindPasswordForm.tsx
  src/components/find/password/passwordPopup.tsx
  src/components/find/username/ConfirmUsernameForm.tsx
  src/components/find/username/FindUsernameForm.tsx
  src/mocks/mockUser.ts
  src/pages/ChangePassword.tsx
  src/pages/FindPassword.tsx
  src/pages/FindUsername.tsx
  src/types/changePasswordFormTypes.ts
  src/types/findTypes.ts
  src/types/passwordTypes.ts
Labels: Feat

#52 Feat: Footer 제작 및 Page 공통레이아웃 제작
  public/dropDown.svg
  public/logoSfacENblack.svg
  public/snsFacebook.svg
  public/snsInstagram.svg
  public/snsYouTube.svg
  src/components/design/Footer.tsx
  src/components/design/TopGNB.tsx
  src/components/layout/PageLayout.tsx
Labels: Feat

#56 Fix: 파일명 변경 및 스타일 코드 변경
  src/components/banner/Banner.styles.ts
  src/components/banner/Banner.tsx
  src/components/banner/NextArrow.tsx
  src/components/banner/PrevArrow.tsx
  src/components/carousel/Banner.tsx
  src/components/portfolio/PortfolioList.tsx
Labels: Fix

#57 Style: 컴포넌트 하단 여백 추가
  src/components/layout/UsersLayout.tsx
Labels: Style

#59 Feat: 추천 크리에이터 슬라이드 구현
  public/recommendProfile01.png
  public/recommendProfile02.png
  public/recommendProfile03.png
  public/recommendThumbnail01.png
  public/recommendThumbnail02.png
  public/recommendThumbnail03.png
  public/recommendThumbnail04.png
  public/recommendThumbnail05.png
  public/recommendThumbnail06.png
  public/recommendThumbnail07.png
  public/recommendThumbnail08.png
  public/recommendThumbnail09.png
  src/components/recommendCreator/ArrowButton.tsx
  src/components/recommendCreator/LeftContainer.tsx
  src/components/recommendCreator/ProductsList.tsx
  src/components/recommendCreator/RecommendCreator.tsx
  src/components/recommendCreator/RecommendProfileCard.tsx
  src/components/recommendCreator/RightContainer.tsx
  src/constants/recommendCreator.ts
  src/types/recommendCreatorType.ts
Labels: Feat

#61 Feat: 전문가 피드백 슬라이드 구현
  public/checkCircle.svg
  public/leftButtonSkyblue.svg
  public/professional/profile_1.png
  public/professional/profile_2.png
  public/professional/profile_3.png
  public/professional/profile_4.png
  public/professional/profile_5.png
  public/professional/thumbnail_1_1.png
  public/professional/thumbnail_1_2.png
  public/professional/thumbnail_1_3.png
  public/professional/thumbnail_2_1.png
  public/professional/thumbnail_2_2.png
  public/professional/thumbnail_2_3.png
  public/professional/thumbnail_3_1.png
  public/professional/thumbnail_3_2.png
  public/professional/thumbnail_3_3.png
  public/professional/thumbnail_4_1.png
  public/professional/thumbnail_4_2.png
  public/professional/thumbnail_4_3.png
  public/professional/thumbnail_5_1.png
  public/professional/thumbnail_5_2.png
  public/professional/thumbnail_5_3.png
  public/rightButtonSkyblue.svg
  src/components/professional/ProfessionalBox.tsx
  src/components/professional/ProfessionalList.tsx
  src/mocks/mockProfessional.ts
  src/types/professionalTypes.ts
Labels: Feat

#62 Feat: Main page 제작
  public/checkPrimary.svg
  public/filterPrimary.svg
  public/filterWhite.svg
  src/components/filterPopup/FilterPopup.tsx
  src/components/filterPopup/PopupCategory.tsx
  src/components/filterPopup/PopupMenus.tsx
  src/pages/Home.tsx
Labels: Feat

#64 Feat: 페이지별 공통 레이아웃 추가
  src/App.tsx
  src/pages/Community.tsx
  src/pages/Portfolio.tsx
  src/pages/Projects.tsx
Labels: Feat

#65 [Feature] 현재 모집중인 프로젝트 구현
  public/currentProject/ProjectTeamMemberProfile1-1.png
  public/currentProject/ProjectTeamMemberProfile1-2.png
  public/currentProject/ProjectTeamMemberProfile1-3.png
  public/currentProject/projectThumbnail1.png
  public/currentProject/projectThumbnail2.png
  public/currentProject/projectThumbnail3.png
  public/currentProject/projectThumbnail4.png
  public/ddayNeutral.svg
  public/ddayPrimary.svg
  public/ddayWarning.svg
  public/heartFillBlue.svg
  public/heartFillYellow.svg
  src/components/currentProject/CurrentProject.tsx
  src/components/currentProject/ProjectCard.tsx
  src/components/currentProject/ProjectTab.tsx
  src/components/currentProject/Projects.tsx
  src/components/currentProject/TeamMemberProfile.tsx
  src/components/design/Badge.tsx
  src/components/design/Card.tsx
  src/components/design/Profile.tsx
  src/components/design/Tabs.tsx
  src/mocks/mockProject.ts
  src/types/projectTypes.ts
  tailwind.config.ts
Labels: Feat

#67 Feat: Floating Button 구현
  public/cancelWhite.svg
  public/communication.svg
  public/compass.svg
  public/plusWhite.svg
  src/components/design/ButtonWithIcon.tsx
  src/components/design/FloatingButton.tsx
  src/types/buttonWithIconTypes.ts
Labels: Feat

#63 Feat: Main page 내부 컴포넌트 분리
  src/components/design/Footer.tsx
  src/components/home/FilterButton.tsx
  src/components/home/FilterTag.tsx
  src/components/home/RegisterInfo.tsx
  src/components/home/RegisterInfoButton.tsx
  src/pages/Home.tsx
  src/types/homeTypes.ts
Labels: Feat

#68 Update: portfolio 피드백 반영
  src/components/portfolio/PortfolioBox.tsx
  src/mocks/mockPortfolio.ts
Labels: Update

#70 Feat: 직업별 카테고리 슬라이드 및 팝업 구현
  public/categoryJobs/arrowLeft.svg
  public/categoryJobs/arrowLeftActived.svg
  public/categoryJobs/arrowRight.svg
  public/categoryJobs/arrowRightActived.svg
  public/categoryJobs/characterDesign.png
  public/categoryJobs/craft.png
  public/categoryJobs/digitalArt.png
  public/categoryJobs/editingBranding.png
  public/categoryJobs/fineArt.png
  public/categoryJobs/graphicDesign.png
  public/categoryJobs/illustration.png
  public/categoryJobs/imageMotionGraphics.png
  public/categoryJobs/listActived.svg
  public/categoryJobs/listDefault.svg
  public/categoryJobs/openCharacterDesign.png
  public/categoryJobs/openCraft.png
  public/categoryJobs/openDigitalArt.png
  public/categoryJobs/openEditingBranding.png
  public/categoryJobs/openFineArt.png
  public/categoryJobs/openGraphicDesign.png
  public/categoryJobs/openIllustration.png
  public/categoryJobs/openImageMotionGraphics.png
  public/categoryJobs/openPhotography.png
  public/categoryJobs/openProductPackage.png
  public/categoryJobs/openProjectPlanning.png
  public/categoryJobs/openTypograghy.png
  public/categoryJobs/openUXUI.png
  public/categoryJobs/photography.png
  public/categoryJobs/productPackage.png
  public/categoryJobs/projectPlanning.png
  public/categoryJobs/typograghy.png
  public/categoryJobs/uxui.png
  src/components/jobsCategory/CategoryListPopup.tsx
  src/components/jobsCategory/CategoryListSlide.tsx
  src/components/jobsCategory/ModalContainer.tsx
  src/components/jobsCategory/ModalPopup.tsx
  src/components/jobsCategory/NextArrowButton.tsx
  src/components/jobsCategory/PrevArrowButton.tsx
  src/constants/categoryJobs.ts
  src/hooks/useThrottle.tsx
  tailwind.config.ts
Labels: Feat

#71 Update: successfull portfolio 피드백 반영
  public/successful/corporateGoogle.png
  public/successful/corporateKakao.png
  public/successful/corporateNaver.png
  public/successful/corporateSamsung.png
  public/successful/successfulThumbnail1.png
  public/successful/successfulThumbnail2.png
  public/successful/successfulThumbnail3.png
  public/successful/successfulThumbnail4.png
  public/successful/successfulThumbnail5.png
  public/successful/winner1.png
  public/successful/winner2.png
  public/successful/winner3.png
  public/successful/winner4.png
  public/successful/winner5.png
  src/components/recommendCreator/RecommendCreator.tsx
  src/components/recommendCreator/RightContainer.tsx
  src/components/successfulPortfolio/ArrowButton.tsx
  src/components/successfulPortfolio/LeftContainer.tsx
  src/components/successfulPortfolio/RightContainer.tsx
  src/components/successfulPortfolio/SuccessfulPortfolio.styles.ts
  src/components/successfulPortfolio/SuccessfulPortfolio.tsx
  src/constants/SuccessfulPortfolio.ts
Labels: Update

#74 Feat: filter popup 구현
  public/filterActive.svg
  public/filterArrowActive.svg
  public/filterArrowDefault.svg
  public/filterDefault.svg
  public/filterRecommendActive.svg
  public/filterRecommendDefault.svg
  src/components/filterPopup/FilterButton.tsx
  src/components/filterPopup/FilterPopupButton.tsx
  src/components/filterPopup/FilterRecommend.tsx
  src/components/filterPopup/FilterSort.tsx
  src/pages/Portfolio.tsx
  src/types/filterButtonTypes.ts
  src/types/filterPopupButtonTypes.ts
Labels: Feat

#75 [Feature] 포트 폴리오 메인페이지의 작업 색상 사용 툴
  public/afterEfectsIcon.svg
  public/blenderIcon.svg
  public/figmaIcon.svg
  public/illustIcon.svg
  public/photoshopIcon.svg
  public/toolSearch.svg
  src/components/portfolio/UsedTool.tsx
  src/components/portfolio/WorkColor.tsx
Labels: Feat

#77 [Feature] 포트폴리오 상세페이지의 프로필 tooltip 구현
  src/components/currentProject/ProjectCard.tsx
  src/components/currentProject/TeamMemberAvatar.tsx
  src/components/design/Avatar.tsx
  src/components/design/Button.tsx
  src/components/portfolio/SocialProfile.tsx
  src/components/portfolio/Tooltip.tsx
  src/mocks/mockUser.ts
  src/types/profileTypes.ts
Labels: Feat

#79 Feat: 포트폴리오 디테일 페이지 작성
  public/figmaIcon.svg
  public/illustratorIcon.svg
  public/photoshopIcon.svg
  public/portfolio/attributionNeutral.svg
  public/portfolio/copyrightNeutral.svg
  public/portfolio/nextArrow.svg
  public/portfolio/porfolioContents_1.png
  public/portfolio/profile_1.png
  public/portfolio/profile_10.png
  public/portfolio/profile_11.png
  public/portfolio/profile_12.png
  public/portfolio/profile_13.png
  public/portfolio/profile_14.png
  public/portfolio/profile_15.png
  public/portfolio/profile_16.png
  public/portfolio/profile_2.png
  public/portfolio/profile_3.png
  public/portfolio/profile_4.png
  public/portfolio/profile_5.png
  public/portfolio/profile_6.png
  public/portfolio/profile_7.png
  public/portfolio/profile_8.png
  public/portfolio/profile_9.png
  public/portfolio/relatedPortfolioThumbnail-1.png
  public/portfolio/relatedPortfolioThumbnail-2.png
  public/portfolio/relatedPortfolioThumbnail-3.png
  public/portfolio/relatedPortfolioThumbnail-4.png
  public/submitIcon.svg
  src/App.tsx
  src/components/portfolioDetail/NextArrow.tsx
  src/components/portfolioDetail/PrevArrow.tsx
  src/components/portfolioDetail/SliderItem.tsx
  src/mocks/mockPortfolioDetail.ts
  src/pages/Portfolio.tsx
  src/pages/PortfolioDetail.tsx
  src/types/portfolioDetailTypes.ts
Labels: Feat

#81 Feat: 저장폴더 팝업 구현
  public/saveThumbnail_1.png
  public/saveThumbnail_2.png
  public/saveThumbnail_3.png
  public/saveThumbnail_4.png
  src/components/portfolio/SavePopup.tsx
  src/mocks/mockSaveFolder.ts
  src/types/saveFolderTypes.ts
Labels: Feat

#82 Feat: 로그인후 로직 구현
  public/alarmIcon.svg
  public/messageIcon.svg
  public/portfolio/portfolioThumbnail_Login_1.png
  public/portfolio/portfolioThumbnail_Login_10.png
  public/portfolio/portfolioThumbnail_Login_11.png
  public/portfolio/portfolioThumbnail_Login_12.png
  public/portfolio/portfolioThumbnail_Login_13.png
  public/portfolio/portfolioThumbnail_Login_14.png
  public/portfolio/portfolioThumbnail_Login_15.png
  public/portfolio/portfolioThumbnail_Login_16.png
  public/portfolio/portfolioThumbnail_Login_2.png
  public/portfolio/portfolioThumbnail_Login_3.png
  public/portfolio/portfolioThumbnail_Login_4.png
  public/portfolio/portfolioThumbnail_Login_5.png
  public/portfolio/portfolioThumbnail_Login_6.png
  public/portfolio/portfolioThumbnail_Login_7.png
  public/portfolio/portfolioThumbnail_Login_8.png
  public/portfolio/portfolioThumbnail_Login_9.png
  public/portfolio/profile_Login_1.png
  public/portfolio/profile_Login_10.png
  public/portfolio/profile_Login_11.png
  public/portfolio/profile_Login_12.png
  public/portfolio/profile_Login_13.png
  public/portfolio/profile_Login_14.png
  public/portfolio/profile_Login_15.png
  public/portfolio/profile_Login_16.png
  public/portfolio/profile_Login_2.png
  public/portfolio/profile_Login_3.png
  public/portfolio/profile_Login_4.png
  public/portfolio/profile_Login_5.png
  public/portfolio/profile_Login_6.png
  public/portfolio/profile_Login_7.png
  public/portfolio/profile_Login_8.png
  public/portfolio/profile_Login_9.png
  src/components/currentProject/ProjectCard.tsx
  src/components/design/TopGNB.tsx
  src/components/portfolio/PortfolioBox.tsx
  src/components/portfolio/PortfolioList.tsx
  src/mocks/mockPortfolio.ts
  src/pages/Home.tsx
Labels: Feat

#85 Feat: 디테일 페이지 플로팅 버튼 구현
  public/checkBlue.svg
  public/closeBlack.svg
  public/contentsFloatingActive.svg
  public/contentsFloatingDefault.svg
  public/deleteFloating.svg
  public/detailProfile.png
  public/editFloating.svg
  public/likeFloatingActive.svg
  public/likeFloatingDefault.svg
  public/shareFloating.svg
  public/shareThumbnail.png
  public/suggestFloating.svg
  src/components/design/DetailFloatingButton.tsx
  src/components/design/DetailFloatingButtonList.tsx
  src/types/detailFloatingButtonTypes.ts
Labels: Feat

#88 Update: 컴포넌트 이름 수정
  src/components/ProjectHome/ProjectTeamMemberProfile.tsx
Labels: Update, Style

#89 [Feature] 커뮤니티 페이지 퍼블리싱
  public/adBanner.svg
  public/arrowDown.svg
  public/basicAvatar.svg
  public/community/aladin.png
  public/community/class101.png
  public/community/daangn.png
  public/community/everytime.png
  public/community/gmarket.png
  public/community/myrealtrip.png
  public/community/pillyze.png
  public/community/ridi.png
  public/community/tving.png
  public/community/udemy.png
  src/components/community/CommunityPostButton.tsx
  src/components/community/CommunitySidebar.tsx
  src/components/community/CommunityTab.tsx
  src/components/community/home/AdvertisingBanner.tsx
  src/components/community/home/AskHelp.tsx
  src/components/community/home/BestPost.tsx
  src/components/community/home/NewPost.tsx
  src/components/community/home/RecruitInfo.tsx
  src/components/community/home/WeeklyPopularTopics.tsx
  src/components/community/post/Pagenation.tsx
  src/components/community/post/PopularKeyword.tsx
  src/components/community/post/PopularPost.tsx
  src/components/community/post/PostFilter.tsx
  src/components/community/post/PostList.tsx
  src/components/community/recruit/RecommendedNotice.tsx
  src/components/community/recruit/RecruitFilter.tsx
  src/components/community/recruit/RecruitNotice.tsx
  src/components/design/Avatar.tsx
  src/pages/Community.tsx
Labels: Feat

#90 Feat: 프로젝트 모집하기 버튼 추가
  public/projectHome/loading.svg
  public/projectHome/recruitmentIcon.svg
  src/components/ProjectHome/ProjectCard.tsx
  src/components/ProjectHome/ProjectList.tsx
  src/components/ProjectHome/ProjectRecruitment.tsx
  src/components/ProjectHome/ProjectTeamMemberProfile.tsx
  src/pages/Projects.tsx
Labels: Style

#94 [Fix] 작업 색상 나오지않는 오류 해결
  src/components/portfolio/WorkColor.tsx
Labels: Fix
